version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 89631139
      MYSQL_DATABASE: gamelist_db
      MYSQL_USER: hygino
      MYSQL_PASSWORD: 89631139
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
